sspring.application.name=todo-list

spring.datasource.url=jdbc:postgresql://dpg-d8fa1md7vvec7385sb
spring.datasource.username=root
spring.datasource.password=123@Ishita

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080